name: Build xdiff

on: [ push ]

permissions:
  contents: write

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew androidZip
      - uses: actions/upload-artifact@v4
        with:
          name: xdiff-android
          path: build/archives/xdiff-android.zip

  linux:
    name: Linux
    container:
      image: gcc:8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: apt-get update
      - run: apt-get install -y cmake
      - run: apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew linuxZip
      - uses: actions/upload-artifact@v4
        with:
          name: xdiff-linux
          path: build/archives/xdiff-linux.zip

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew appleZip
      - uses: actions/upload-artifact@v4
        with:
          name: xdiff-apple
          path: build/archives/xdiff-apple.zip

  publish-release-with-files:
    name: Create Publication
    needs: [android, linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@v4
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew mergeZips
      - uses: actions/upload-artifact@v4
        with:
          name: xdiff
          path: build/archives/xdiff.zip
      - name: Set current date as env variable
        id: set_date
        run: echo "NOW=$(date +'%Y%m%dT%H%M%S')Z" >> $GITHUB_OUTPUT
      - run: tree
      - uses: softprops/action-gh-release@v2
        with:
          files: build/archives/xdiff.zip
          name: v${{ steps.set_date.outputs.NOW }}-SNAPSHOT
          tag_name: ${{ steps.set_date.outputs.NOW }}
          draft: false
          prerelease: false
